version: '3.6'

services:
  proxy:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy

  front:
    build: ./front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    networks:
      - proxy

  survey_service:
    build: ./services/surveys
    environment:
      - PORT=80
      - "MONGODB_URI=${MONGODB_URI}"
      - "JWT_RS256_PUB_KEY=${JWT_RS256_PUB_KEY}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.survey-service.rule=(Host(`localhost`) && PathPrefix(`/api/survey`))"
      - "traefik.http.routers.survey-service.entrypoints=web"
      - "traefik.http.services.survey-service.loadbalancer.server.port=80"
    networks:
      - proxy

  auth_service:
    build: ./services/auth
    environment:
      - PORT=80
      - "MONGODB_URI=${MONGODB_URI}"
      - "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}"
      - "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}"
      - "GOOGLE_CALLBACK=${GOOGLE_CALLBACK}"
      - "JWT_RS256_PASSPHRASE=${JWT_RS256_PASSPHRASE}"
      - "JWT_RS256_PRIV_KEY=${JWT_RS256_PRIV_KEY}"
      - "JWT_RS256_PUB_KEY=${JWT_RS256_PUB_KEY}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=(Host(`localhost`) && (PathPrefix(`/api/user`) || PathPrefix(`/api/auth`)))"
      - "traefik.http.routers.auth-service.entrypoints=web"
      - "traefik.http.services.auth-service.loadbalancer.server.port=80"
    networks:
      - proxy
  

networks:
  proxy: