name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx for Auth
        uses: docker/setup-buildx-action@v2
        id: builder-auth
      -
        name: Set up Docker Buildx for Survey
        uses: docker/setup-buildx-action@v2
        id: builder-survey
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Auth
        id: docker-build-auth
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.builder-auth.outputs.name }}
          context: ./services/auth
          file: ./services/auth/Dockerfile
          push: true
          tags: patoguereque/semanai-auth-service:latest
      -
        name: Build and push Surveys
        id: docker-build-surveys
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.builder-surveys.outputs.name }}
          context: ./services/surveys
          file: ./services/surveys/Dockerfile
          push: true
          tags: patoguereque/semanai-surveys-service:latest