name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./services/auth
          push: true
          tags: patoguereque/semanai-auth-service:latest
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./services/survey
          push: true
          tags: patoguereque/semanai-survey-service:latest